version: '3.9'
services:

        
  backend:
    
    build: ./backend
    restart: always

    volumes:
       - springBootLogs:/var/log/spring-boot
    ports:
      - 8090:8090
  

  frontend:
    
    build: ./frontend
    ports:
      - 8082:80
