version: '3.9'
services:

        
  backend:
    depends_on:
      - db
    build: ./backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
    volumes:
       - springBootLogs:/var/log/spring-boot
    ports:
      - 8090:8090
    networks:
      - backend-network

  frontend:
    depends_on:
      - db
    build: ./frontend
    ports:
      - 8082:80
networks:
  backend-network:
    external: true
volumes:
  db_data:  # Define the named volume here
  springBootLogs: